# Generated by Django 4.0.3 on 2022-03-16 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registeredUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('emailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('registerDate', models.DateField(default=datetime.date(2022, 3, 16))),
                ('phoneNumber', models.CharField(max_length=10, null=True)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
