# Generated by Django 4.0.3 on 2022-03-17 19:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('registerDate', models.DateField(default=datetime.date(2022, 3, 17))),
            ],
        ),
        migrations.CreateModel(
            name='tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolname', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='registerDate',
            field=models.DateField(default=datetime.date(2022, 3, 17)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewDate',
            field=models.DateField(default=datetime.date(2022, 3, 17)),
        ),
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.tools')),
            ],
        ),
    ]
