# Generated by Django 4.0.3 on 2022-03-21 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_blogs_tools_alter_registeredusers_registerdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='registerDate',
            field=models.DateField(default=datetime.date(2022, 3, 21)),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='registerDate',
            field=models.DateField(default=datetime.date(2022, 3, 21)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewDate',
            field=models.DateField(default=datetime.date(2022, 3, 21)),
        ),
    ]
