# Generated by Django 4.0.3 on 2022-05-12 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_tutorials_alter_blogs_registerdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='confirmpassword',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='f', max_length=1),
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='registerDate',
            field=models.DateField(default=datetime.date(2022, 5, 12)),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='registerDate',
            field=models.DateField(default=datetime.date(2022, 5, 12)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewDate',
            field=models.DateField(default=datetime.date(2022, 5, 12)),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='uploadingDate',
            field=models.DateField(default=datetime.date(2022, 5, 12)),
        ),
    ]
