# Generated by Django 4.0.3 on 2022-05-21 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_registeredusers_city_registeredusers_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='registerDate',
            field=models.DateField(default=datetime.date(2022, 5, 21)),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='registerDate',
            field=models.DateField(default=datetime.date(2022, 5, 21)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewDate',
            field=models.DateField(default=datetime.date(2022, 5, 21)),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='uploadingDate',
            field=models.DateField(default=datetime.date(2022, 5, 21)),
        ),
    ]
